export default [
  { id: 1, type: 'text', author: "me", data: { text: "Why don't they have salsa on the table?" } },
  { id: 2, type: 'text', author: "them", data: { text: "What do you need salsa for?" } },
  { id: 3, type: 'text', author: "me", data: { text: "Salsa is now the number one condiment in America." } },
  { id: 4, type: 'text', author: "them", data: { text: "You know why? Because people like to say 'salsa.' 'Excuse me, do you have salsa?' 'We need more salsa.' 'Where is the salsa? No salsa?'" } },
  { id: 5, type: 'text', author: "me", data: { text: "You know it must be impossible for a Spanish person to order seltzer and not get salsa. 'I wanted seltzer, not salsa.'" } },
  { id: 6, type: 'text', author: "them", data: { text: "Don't you know the difference between seltzer and salsa?? You have the seltezer after the salsa!" } },
  { id: 7, type: 'text', author: "me", data: { text: "See, this should be a show. This is the show. " } },
  { id: 8, type: 'text', author: "them", data: { text: "What?" } },
  { id: 9, type: 'text', author: "me", data: { text: "This. Just talking." } },
  { id: 10, type: 'text', author: "them", data: { text: "Yeah, right." } },
  { id: 11, type: 'text', author: "me", data: { text: "I'm really serious. I think that's a good idea. " } },
  { id: 12, type: 'text', author: "them", data: { text: "Just talking? Well what's the show about?" } },
  { id: 13, type: 'text', author: "me", data: { text: "It's about nothing." } },
  { id: 14, type: 'text', author: "them", data: { text: "No story?" } },
  { id: 15, type: 'file', author: "them", data: { text: "No forget the story. ", file: { name: 'file.mp3', url: '#' } } },
  { id: 16, type: 'file', author: "me", data: { text: "What about this one instead?? ", file: { name: 'song.mp3', url: '#' } } },
  { id: 17, type: 'text', author: "them", data: { text: "Open up the dev tools and go to the console section to check some cool events attached to the component", meta: 'Read' } },
  { id: 18, type: 'emoji', author: "me", data: { emoji: "😋" } },
]